package com.agungsetiawan.saveimagedb.ui;

import com.agungsetiawan.saveimagedb.domain.Book;
import com.agungsetiawan.saveimagedb.service.BookService;
import com.agungsetiawan.saveimagedb.tablemodel.BookTableModel;
import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.apache.commons.io.FileUtils;
import saveimagedb.SaveImageDB;

/**
 *
 * @author awanlabs
 */
public class UploadImageFrame extends javax.swing.JFrame {
   
   BookService bookService;
   BookTableModel bookTableModel;
   File file;
   JFileChooser jfc;
    
    public UploadImageFrame() {
        initComponents();
        initTable();
    }
    
    private void initTable(){
        jTableBook.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                try {
                    int row=jTableBook.getSelectedRow();
                    Book book=bookTableModel.findOne(row);
                    
                    Toolkit toolkit=Toolkit.getDefaultToolkit();
                    
                    String path=new File(".").getCanonicalPath();
                    Image image=toolkit.getImage(path+"/image/"+book.getImage());
    //                Image image=toolkit.getImage(getClass().getResource("/image/"+book.getImage()));
                    Image imagedResized=image.getScaledInstance(200, 250, Image.SCALE_DEFAULT);
                    ImageIcon icon=new ImageIcon(imagedResized);
                    jLabelGambar.setIcon(icon);
                } catch (IOException ex) {
                    Logger.getLogger(UploadImageFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
            bookService=SaveImageDB.getBookService();
            bookTableModel=new BookTableModel(bookService.findAll());
            jTableBook.setModel(bookTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGambar = new javax.swing.JLabel();
        jButtonPilihGambar = new javax.swing.JButton();
        jButtonSimpanGambar = new javax.swing.JButton();
        jLabelNamaFileBuku = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBook = new javax.swing.JTable();
        jTextFieldTitle = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelGambar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelGambar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonPilihGambar.setText("Pilih Gambar");
        jButtonPilihGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPilihGambarActionPerformed(evt);
            }
        });

        jButtonSimpanGambar.setText("Simpan");
        jButtonSimpanGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanGambarActionPerformed(evt);
            }
        });

        jLabelNamaFileBuku.setText("Gambar Buku");

        jTableBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableBook);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldTitle)
                    .addComponent(jLabelGambar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jLabelNamaFileBuku)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPilihGambar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSimpanGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNamaFileBuku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabelGambar, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPilihGambar)
                    .addComponent(jButtonSimpanGambar))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPilihGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPilihGambarActionPerformed
        jfc=new JFileChooser();
        if(jfc.showOpenDialog(jLabelGambar)==JFileChooser.APPROVE_OPTION){
            
            Toolkit toolkit=Toolkit.getDefaultToolkit();
            Image image=toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image imagedResized=image.getScaledInstance(200, 250, Image.SCALE_DEFAULT);
            ImageIcon imageIcon=new ImageIcon(imagedResized);
            
            jLabelGambar.setIcon(imageIcon);
            jLabelNamaFileBuku.setText(jfc.getSelectedFile().getName());
            
            file=new File(jfc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_jButtonPilihGambarActionPerformed

    private void jButtonSimpanGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanGambarActionPerformed
        Book book=new Book();
        book.setTitle(jTextFieldTitle.getText());
        book.setImage(jLabelNamaFileBuku.getText());
        bookService.save(book);
        bookTableModel.save(book);
        try {
            String path=new File(".").getCanonicalPath();
            FileUtils.copyFileToDirectory(file, new File(path+"/image"));
        } catch (IOException ex) {
            Logger.getLogger(UploadImageFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSimpanGambarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UploadImageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UploadImageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UploadImageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UploadImageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UploadImageFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPilihGambar;
    private javax.swing.JButton jButtonSimpanGambar;
    private javax.swing.JLabel jLabelGambar;
    private javax.swing.JLabel jLabelNamaFileBuku;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBook;
    private javax.swing.JTextField jTextFieldTitle;
    // End of variables declaration//GEN-END:variables
}
